spring:
  application:
    name: Hiker
  datasource:
    url: jdbc:h2:mem:hiker;
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8888
